### PR TITLE
dimensionality reduction script

### PR DESCRIPTION
**Pull request by cheesinglee**

### CODE REVIEW

**Comment by jaor** [comment]
it'd be nice to have a test too :)

**Comment by cheesinglee** [comment]
Oh shoot, I'll get on that

**Review by jaor — DISMISSED** [review]
looks good, thanks!

**Comment by jaor** [comment]
@cheesinglee one more thing before merging: we need entries for the script at the top level's metadata.json and readme.md

**Comment by cheesinglee** [comment]
top-level info added

**Review by jaor — APPROVED** [review]

**Pull request merged**
