### PR TITLE
new sliding-window script

### PR DESCRIPTION
**Pull request by cheesinglee**
I wrote this script to help me with a little analysis I was working on, and I figured it would make a good example script. 

This is my first contribution to this repo, so let me know if I've left something out.

### CODE REVIEW

**Comment by akashenfelter** [comment]
I'm getting the test error "KO: no dataset found in results", even though whizzml_results.json is where it expects it to be. Something wrong with my setup?

**Comment by cheesinglee** [comment]
What is the output of this command, if you run it from `sliding-window/test`?

`grep -Po 'dataset/[0-9a-f]{24}' cmd/exec/whizzml_results.json|head -1`

**Comment by akashenfelter** [comment]
`usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]`

**Comment by cheesinglee** [comment]
Looks like the -P flag is not supported in Mac OS's version of grep. Can you see if it works now?

**Comment by akashenfelter** [comment]
Oh, grep.

That works! Merging...

**Pull request merged**
