### PR TITLE
gradient-boosting: shorter resource names

### PR DESCRIPTION
**Pull request by jaor**
i closed the previous one and rebased.

### CODE REVIEW

**Comment by jaor** [comment]
@charleslparker i've added an optional flag to smacdown-ensemble to control intermediate resource deletion

**Comment by jaor** [comment]
@charleslparker ping?

**Comment by charleslparker** [comment]
I'll have it done by day's end I swear!

**Comment by charleslparker** [comment]
This all works, but I don't have permissions to push to this repo!

**Comment by jaor** [comment]
oh, my bad, sorry! i just sent you an invitation for the correct group.

**Pull request merged**
