### PR TITLE
cross-validation: added delete intermediate resources

### PR DESCRIPTION
**Pull request by akashenfelter**
Adds a 'delete-resources' boolean so the user can decide to delete all intermediate resources after running the script. (As requested by @osroca)

### CODE REVIEW

**Comment by osroca** [comment]
@akashenfelter I would take the chance to improve a bit the descriptions of the scripts with, at least, the link to the README in github.

**Comment by mmerce** [comment]
Looks good and tests pass, so I can merge if you want. However, improving the descriptions of the scritps is a good idea...

**Comment by akashenfelter** [comment]
I've expanded the descriptions, and it's even in properly formatted json this time. Ready to go!

**Comment by osroca** [comment]
@akashenfelter I don't think the formatting of the description is the proper one, at least for the LR... it should be markdown and I'm seeing som `<br>` in them. The best way to define de description is to import the script directly in bigml and create it and look at the resulting description.

image

This is the markdown description I think you wanted to put in place (for LR)
```
"The objective of this script is to perform a k-fold cross validation of a\n logistic regression built from a dataset. The algorithm:\n\n - Divides the dataset in k parts\n - Holds out the data in one of the parts and builds a logistic regression\n with the rest of data\n - Evaluates the logistic regression with the hold out data  - The second and third steps are repeated with each of the k parts, so that  k evaluations are generated\n - Finally, the evaluation metrics are averaged to provide the cross-validation  metrics.\n\nThe **output** of the script will be an `evaluation ID`. This evaluation is a  cross-validation, meaning that its metrics are averages of the k evaluations  created in the cross-validation process.\n\nFor more information, please see the [readme](https://github.com/whizzml/examples/tree/master/cross-validation/logistic-regression)."
```

**Comment by akashenfelter** [comment]
Good catch. The logistic-regression metadata has been fixed, the others were ok.

**Comment by osroca** [comment]
oh! I was lucky then ... thanks

**Comment by mmerce** [comment]
I understand now it's ready to go? Do you want me to retest and merge? Once it's merge, I understand that you @akashenfelter will pubish the script in the gallery, right?

By the way, Jaime has suggested adding the valid values or ranges to the arguments in all the crossvalidation scripts. This could be done in a separate PR.

**Comment by whizzmler** [comment]
Let's go ahead and merge this one and open a new one for adding suggested
ranges to the arguments. Once that is in, I'll add them all to the gallery.
Would you be able to make those suggestions?

 It's actually a little tricky to change a script that has already been
shared in the gallery -- Oscar is hunting down how it has been done in the
past -- so while I can add in boosted ensembles, logistic regression, and
deepnets right away, it may take a bit before the changes to the ensemble
script are available.

Allison

**Pull request merged**
